/** Unit proofs for lockfile verification plumbing. */

import { afterEach, describe, expect, test } from "bun:test";

import { pnpmAdapter } from "../src/adapters/pnpm.ts";
import { LockfileVerificationError, lockfileDifference, verifyLockfile } from "../src/transaction/lockfile-verify.ts";
import { cleanupFixtures, read, scratchDirectory, write } from "./support/fixture-repo.ts";
import { LOCKFILE, verify } from "./support/lockfile-verify-fixture.ts";

describe("lockfile verification plumbing", () => {
  afterEach(cleanupFixtures);

  test("the command is the adapter's, and it is the one that writes no node_modules", () => {
    // The engine may not name a package manager, so this is the only place the
    // string is allowed to exist — and `--lockfile-only`, not the install
    // command, is what makes running it inside a symlinked worktree safe.
    expect(pnpmAdapter.lockfileOnlyCommand()).toEqual(["pnpm", "install", "--lockfile-only"]);
    expect(pnpmAdapter.lockfileOnlyCommand()).not.toEqual(pnpmAdapter.installCommand());
  });

  test("passes when the regenerated bytes agree, and the agreement is not a command that did nothing", () => {
    const root = scratchDirectory();
    write(root, LOCKFILE, "importers:\n\n  apps/api: {}\n");
    // The stand-in truncates and rewrites the file, so a passing result means
    // the bytes were compared, not that the lockfile was never touched.
    const result = verify(root, ["sh", "-c", `: > ${LOCKFILE}; printf 'importers:\\n\\n  apps/api: {}\\n' > ${LOCKFILE}`]);

    expect(result.ok).toBe(true);
    expect(result.differences).toBeUndefined();
    expect(result.lockfile).toBe(LOCKFILE);
  });

  test("reports a mismatch with the file, the line, and a bounded excerpt of both sides", () => {
    const root = scratchDirectory();
    const planned = ["importers:", "", "  apps/api:", "    dependencies: {}", ""].join("\n");
    write(root, LOCKFILE, planned);

    const result = verify(root, ["sh", "-c", `printf 'importers:\\n\\n  apps/api: {}\\n' > ${LOCKFILE}`]);

    expect(result.ok).toBe(false);
    expect(result.command).toBe(`sh -c printf 'importers:\\n\\n  apps/api: {}\\n' > ${LOCKFILE}`);
    expect(result.differences?.[0]).toBe(`${LOCKFILE} line 3: 2 planned line(s) against 1 regenerated`);
    expect(result.differences).toContain("-  apps/api:");
    expect(result.differences).toContain("+  apps/api: {}");
  });

  test("keeps the plan's bytes, so what runs after it is still the plan", () => {
    const root = scratchDirectory();
    const planned = "importers:\n\n  apps/api:\n    dependencies: {}\n";
    write(root, LOCKFILE, planned);

    expect(verify(root, ["sh", "-c", `printf 'rewritten\\n' > ${LOCKFILE}`]).ok).toBe(false);
    // A gate — or an apply — reading a regenerated lockfile would be describing
    // a tree nobody planned, and would hide the divergence it just found.
    expect(read(root, LOCKFILE)).toBe(planned);
  });

  test("excerpts a large divergence instead of pasting the file", () => {
    const planned = ["header", ...Array.from({ length: 60 }, (_, index) => `  left-${index}`), "footer"].join("\n");
    const regenerated = ["header", ...Array.from({ length: 60 }, (_, index) => `  right-${index}`), "footer"].join("\n");

    const differences = lockfileDifference(planned, regenerated, LOCKFILE);

    expect(differences[0]).toBe(`${LOCKFILE} line 2: 60 planned line(s) against 60 regenerated`);
    expect(differences).toContain("- … 50 more line(s)");
    expect(differences).toContain("+ … 50 more line(s)");
    expect(differences.length).toBeLessThan(30);
    // The unchanged head and tail are not the finding, and repeating them is how
    // a report becomes something nobody reads.
    expect(differences.some((line) => line.includes("header") || line.includes("footer"))).toBe(false);
  });

  test("a package manager that is not there is an error, not a skip", () => {
    const root = scratchDirectory();
    write(root, LOCKFILE, "importers:\n");

    // The operator ran the flag to find out. Returning `ok` here would report a
    // verification that never happened, which is worse than not offering one.
    expect(() => verify(root, ["monocarve-no-such-package-manager", "install", "--lockfile-only"])).toThrow(LockfileVerificationError);
    expect(() => verify(root, ["monocarve-no-such-package-manager", "install"])).toThrow(/needs monocarve-no-such-package-manager on PATH/);
  });

  test("a package manager that fails is an error, and says which command and why", () => {
    const root = scratchDirectory();
    write(root, LOCKFILE, "importers:\n");

    const failed = (() => {
      try {
        verify(root, ["sh", "-c", "echo 'ERR_PNPM_NO_LOCKFILE nothing to resolve' >&2; exit 4"]);
        return undefined;
      } catch (error) {
        return error as Error;
      }
    })();

    expect(failed).toBeInstanceOf(LockfileVerificationError);
    expect(failed?.message).toContain("exit 4");
    expect(failed?.message).toContain("ERR_PNPM_NO_LOCKFILE");
  });

  test("refuses when there is no lockfile to compare rather than calling that agreement", () => {
    const root = scratchDirectory();
    expect(() => verify(root, ["sh", "-c", "true"])).toThrow(/no pnpm-lock\.yaml to compare/);
  });

  test("a completeness finding fails the run even when the bytes agree, and it is read from the plan's bytes", () => {
    const root = scratchDirectory();
    const planned = "importers:\n\n  apps/api: {}\n";
    write(root, LOCKFILE, planned);
    // A command that leaves the file alone: the byte comparison agrees, which
    // is the whole point — this is the state the regenerate-and-compare check
    // cannot fail, so if the completeness finding does not fail it, nothing
    // does.
    const untouched = ["sh", "-c", "true"];

    const clean = verifyLockfile({ workspacePath: root, lockfileName: LOCKFILE, command: untouched, completeness: () => [] });
    expect(clean.ok).toBe(true);
    expect(clean.differences).toBeUndefined();

    const found = verifyLockfile({
      workspacePath: root,
      lockfileName: LOCKFILE,
      command: untouched,
      completeness: () => ["apps/api declares left-pad@1.3.0, and the lockfile has no entry for it"],
    });
    expect(found.ok).toBe(false);
    expect(found.differences).toEqual([`${LOCKFILE}: apps/api declares left-pad@1.3.0, and the lockfile has no entry for it`]);

    // Which bytes it reads, asked where the two differ. The plan's, not the
    // regenerated ones: a check fed the regenerated file would pass a plan
    // whose lockfile the package manager repaired on the way past, and the
    // repair is discarded, so the plan would still land the broken bytes.
    const seen: string[] = [];
    verifyLockfile({
      workspacePath: root,
      lockfileName: LOCKFILE,
      command: ["sh", "-c", `printf 'regenerated\\n' > ${LOCKFILE}`],
      completeness: (text) => {
        seen.push(text);
        return [];
      },
    });
    expect(seen).toEqual([planned]);
  });

  /**
   * The check's own branches, on text rather than on a pnpm run.
   *
   * The pnpm case proves it fires on the one lockfile `--frozen-lockfile`
   * refuses, and that lockfile has no `packages:`/`snapshots:` sections at all.
   * So a check that only worked on *that* shape would pass it — these are the
   * other two shapes, and the resolution-carrying one is the case a real
   * workspace is in.
   */
  test("the completeness check reads the snapshot keys, and abstains on a lockfile shape it cannot read", () => {
    const withSections = (version: string): string =>
      [
        "lockfileVersion: '9.0'",
        "",
        "importers:",
        "",
        "  .: {}",
        "",
        "  libs/analytics:",
        "    dependencies:",
        "      react-dom:",
        "        specifier: 18.3.1",
        `        version: ${version}`,
        "",
        "packages:",
        "",
        "  react-dom@18.3.1:",
        "    resolution: {integrity: sha512-fake}",
        "",
        "snapshots:",
        "",
        "  react-dom@18.3.1(react@18.3.1):",
        "    dependencies:",
        "      react: 18.3.1",
        "",
      ].join("\n");

    // The snapshot key is the peer-suffixed one, so the unsuffixed version has
    // no entry — measured on pnpm 11.17.0 as the same
    // `ERR_PNPM_LOCKFILE_MISSING_DEPENDENCY` a missing `packages:` entry gives,
    // which is why `packages:` alone is not attestation here or in the renderer.
    expect(pnpmAdapter.missingResolutions(withSections("18.3.1"))).toEqual(["libs/analytics declares react-dom@18.3.1, and the lockfile has no entry for it"]);
    expect(pnpmAdapter.missingResolutions(withSections("18.3.1(react@18.3.1)"))).toEqual([]);

    // A lockfile with resolutions and no `snapshots:` section predates the
    // split and is not readable this way; calling every dependency in it broken
    // would be worse than saying nothing.
    const older = withSections("18.3.1").replace(/\nsnapshots:[\s\S]*$/, "\n");
    expect(older).not.toContain("snapshots:");
    expect(pnpmAdapter.missingResolutions(older)).toEqual([]);
  });
});
