/** Markdown helpers shared by the reference generators. */

import { resolve } from "node:path";

export const GENERATED_BANNER = "<!-- generated by scripts/docs/generate.ts; do not edit -->";

export const REPO_ROOT = resolve(import.meta.dir, "../..");

/** A table cell: single line, with `|` escaped so it cannot split the row. */
function cell(text: string): string {
  return text.replace(/\s*\n\s*/gu, " ").replaceAll("|", "\\|");
}

/** Inline code that survives a table cell. */
export function code(text: string): string {
  return `\`${text}\``;
}

export function table(headers: readonly string[], rows: readonly (readonly string[])[]): string {
  const line = (cells: readonly string[]): string => `| ${cells.map(cell).join(" | ")} |`;
  return [line(headers), line(headers.map(() => "---")), ...rows.map(line)].join("\n");
}

/** Capitalized sentence form of a registry summary. */
export function sentence(text: string): string {
  const trimmed = text.trim();
  const capitalized = trimmed.charAt(0).toUpperCase() + trimmed.slice(1);
  return /[.!?]$/u.test(capitalized) ? capitalized : `${capitalized}.`;
}

/** Join blocks with one blank line, dropping empty ones. */
export function blocks(...parts: readonly (string | undefined)[]): string {
  return `${parts
    .filter((part): part is string => part !== undefined && part.trim() !== "")
    .map((part) => part.trim())
    .join("\n\n")}\n`;
}

/**
 * Format with the repository's oxfmt configuration, so the committed file is
 * exactly what `bunx oxfmt` would leave and regenerating is a no-op.
 * `stdinPath` is the repo-relative destination; oxfmt uses it to pick the parser
 * and the configuration that applies.
 */
export function formatMarkdown(markdown: string, stdinPath: string): string {
  const result = Bun.spawnSync([resolve(REPO_ROOT, "node_modules/.bin/oxfmt"), `--stdin-filepath=${stdinPath}`], {
    cwd: REPO_ROOT,
    stdin: new TextEncoder().encode(markdown),
    stdout: "pipe",
    stderr: "pipe",
  });
  if (result.exitCode !== 0) throw new Error(`oxfmt failed for ${stdinPath}: ${result.stderr.toString()}`);
  return result.stdout.toString();
}
